"""Agent definitions for the Martian Data multi-agent workflow."""
from __future__ import annotations

import os
from dataclasses import dataclass
from typing import Dict, Final, List, Literal, Optional, Sequence

from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables import Runnable
from langchain_core.tools import BaseTool
from langchain_ollama import ChatOllama
from pydantic import BaseModel, Field

from . import tools as dataset_tools

DEFAULT_MODEL: Final[str] = os.getenv("OLLAMA_MODEL", "gemma3:1b")
DEFAULT_BASE_URL: Final[str] = os.getenv("OLLAMA_BASE_URL", "http://localhost:11434")
DEFAULT_TEMPERATURE: Final[float] = float(os.getenv("OLLAMA_TEMPERATURE", "0.0") or 0.0)

DEFAULT_DATASET_TOOLS: Sequence[BaseTool] = [
    dataset_tools.herd_dataset_columns,
    dataset_tools.herd_dataset_preview,
    dataset_tools.herd_dataset_summary,
    dataset_tools.filter_herd_dataset,
    dataset_tools.save_processed_dataset,
]

def build_llm(
    *, model: Optional[str] = None, temperature: Optional[float] = None
) -> ChatOllama:
    """Instantiate the base ChatOllama model for all agents."""
    resolved_model = model or DEFAULT_MODEL
    resolved_temperature = temperature if temperature is not None else DEFAULT_TEMPERATURE
    return ChatOllama(
        model=resolved_model,
        base_url=DEFAULT_BASE_URL,
        temperature=resolved_temperature,
    )


class ToolAction(BaseModel):
    """Single planned tool call generated by the task interpreter."""

    tool_name: str = Field(..., description="Name of the tool to execute.")
    arguments: dict = Field(
        default_factory=dict,
        description="Keyword arguments for the tool. Keys should match the tool schema.",
    )
    rationale: str = Field(
        ...,
        description="Short justification for why this tool is relevant.",
    )


class ToolRequest(BaseModel):
    """Description of a tool capability that must be created before execution."""

    tool_name: str = Field(
        ..., description="Proposed name for the new tool (snake_case recommended)."
    )
    template: Literal["llm_country_inference", "custom_python"] = Field(
        ...,
        description=(
            "Template to use when constructing the tool. "
            "'llm_country_inference' creates a row-wise country guesser. "
            "'custom_python' requires the developer to review and implement logic manually."
        ),
    )
    description: str = Field(
        ...,
        description="Plain-language summary of what the tool must accomplish.",
    )
    input_fields: List[str] = Field(
        default_factory=list,
        description="Key inputs the tool expects (e.g., column names).",
    )
    guardrails: str = Field(
        ...,
        description="Safety constraints or validation checks the tool should enforce.",
    )


class TaskPlan(BaseModel):
    """Structured plan describing how the system should handle the user request."""

    intent: str = Field(..., description="Natural-language summary of the user's intent.")
    requires_writing: bool = Field(
        False, description="Whether the workflow will write a processed CSV."
    )
    key_columns: List[str] = Field(
        default_factory=list,
        description="Dataset columns that are relevant to this task.",
    )
    tool_requests: List[ToolRequest] = Field(
        default_factory=list,
        description="New tools that must be provisioned before executing the plan.",
    )
    actions: List[ToolAction] = Field(
        default_factory=list,
        description="Ordered tool calls the research agent should consider executing.",
    )
    expected_output_description: str = Field(
        ...,
        description="What the user expects to receive at the end of the workflow.",
    )


class ParserOutput(BaseModel):
    """Structured output produced by the response parser agent."""

    records: List[dict] = Field(
        ...,
        description="List of row dictionaries representing the processed dataset section.",
    )
    filename: Optional[str] = Field(
        default=None,
        description="Suggested filename for the processed dataset. Optional.",
    )
    notes: str = Field(
        ...,
        description="Notes or caveats about the parsed data, including any assumptions made.",
    )


class ResultSummary(BaseModel):
    """Final explanation generated by the result agent."""

    overview: str = Field(..., description="High-level narrative of what happened.")
    data_changes: str = Field(
        ...,
        description="Explanation of how the dataset was read, filtered, or updated.",
    )
    follow_up: str = Field(
        ...,
        description="Recommended next steps or questions for the user.",
    )


def build_task_interpreter_chain(llm: Optional[ChatOllama] = None) -> Runnable:
    """Create the task interpreter chain that outputs a structured TaskPlan."""
    model = llm or build_llm()
    structured_model = model.with_structured_output(TaskPlan)

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                (
                    "You are the Task Interpreter agent for the Martian Data project. "
                    "Given the user's request, explain their intent, decide which dataset "
                    "columns matter, and propose a short ordered list of tool calls. "
                    "You must only rely on the currently available tools: "
                    f"{', '.join(tool.name for tool in DEFAULT_DATASET_TOOLS)}. "
                    "If the request cannot be fulfilled with these tools, add entries to "
                    "`tool_requests` describing the new capability needed and the guardrails "
                    "it must enforce. Prefer the 'llm_country_inference' template for tasks "
                    "that require predicting a country for each dataset row. "
                    "Every plan MUST include at least one action referencing a concrete tool "
                    "name (either an existing tool or one you request). "
                    "Set `requires_writing` to True when a new CSV must be produced. "
                    "If a task is impossible even with a new tool, clearly note that limitation "
                    "in `expected_output_description` and avoid hallucinating results. "
                    "Provide a concise ordered list of actions (max three unless absolutely necessary)."
                ),
            ),
            MessagesPlaceholder(variable_name="chat_history", optional=True),
            ("human", "{user_request}"),
        ]
    )

    return prompt | structured_model


def build_research_summarizer_chain(llm: Optional[ChatOllama] = None) -> Runnable:
    """Create the research agent that reflects on tool outputs and produces JSON."""
    model = llm or build_llm()

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                (
                    "You are the Research Agent. You will receive:\n"
                    "- the user's request\n"
                    "- the high-level task plan\n"
                    "- structured results from tools that were executed\n\n"
                    "Analyze the tool outputs and respond with **valid JSON** containing:\n"
                    '{{\n  "summary": "...",\n  "records": [...],\n  "notes": "..."\n}}\n'
                    "- `summary`: brief narrative of findings and actions taken.\n"
                    "- `records`: array of objects representing new or updated dataset rows (can be empty).\n"
                    "- `notes`: important caveats or follow-up considerations.\n"
                    "Do not wrap the JSON in markdown fences. Ensure it is valid JSON."
                ),
            ),
            (
                "human",
                (
                    "User request:\n{user_request}\n\n"
                    "Task plan:\n{plan_text}\n\n"
                    "Tool execution results (JSON):\n{tool_results}\n\n"
                    "Produce the JSON object now."
                ),
            ),
        ]
    )

    return prompt | model


def build_response_parser_chain(llm: Optional[ChatOllama] = None) -> Runnable:
    """Create the response parser agent that structures research findings."""
    model = llm or build_llm()
    structured_model = model.with_structured_output(ParserOutput)

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                (
                    "You are the Response Parser agent. Convert the research output into a "
                    "clean list of records suitable for a CSV file. Use the column names "
                    "exactly as they appear in the dataset. Suggest a filename if new data "
                    "should be written. Always include concise notes describing assumptions."
                ),
            ),
            ("human", "{research_output}"),
        ]
    )

    return prompt | structured_model


def build_result_agent_chain(llm: Optional[ChatOllama] = None) -> Runnable:
    """Create the result agent that explains the overall workflow."""
    model = llm or build_llm()
    structured_model = model.with_structured_output(ResultSummary)

    prompt = ChatPromptTemplate.from_messages(
        [
            (
                "system",
                (
                    "You are the Result Agent summarizing the entire workflow. "
                    "Explain what steps occurred, how the dataset was affected, "
                    "and suggest any follow-up actions. Keep the tone professional "
                    "and concise."
                ),
            ),
            ("human", "{final_context}"),
        ]
    )

    return prompt | structured_model


@dataclass
class AgentBundle:
    """Convenience container holding all agent components."""

    llm: ChatOllama
    task_interpreter: Runnable
    research_agent: Runnable
    response_parser: Runnable
    result_agent: Runnable


def build_agent_bundle(
    *,
    llm: Optional[ChatOllama] = None,
    tools: Optional[Sequence[BaseTool]] = None,
) -> AgentBundle:
    """Construct and return all configured agents."""
    model = llm or build_llm()
    task_interpreter = build_task_interpreter_chain(model)
    research_agent = build_research_summarizer_chain(model)
    response_parser = build_response_parser_chain(model)
    result_agent = build_result_agent_chain(model)

    return AgentBundle(
        llm=model,
        task_interpreter=task_interpreter,
        research_agent=research_agent,
        response_parser=response_parser,
        result_agent=result_agent,
    )


def base_tool_map() -> Dict[str, BaseTool]:
    """Return a mapping of the default dataset tools by name."""
    return {tool.name: tool for tool in DEFAULT_DATASET_TOOLS}

